const { chromium } = require("../.cinepop-tools/node_modules/@playwright/test");
const fs = require("node:fs");
const http = require("node:http");
const path = require("node:path");
const assert = require("node:assert/strict");
const root = path.resolve(__dirname, "..");
const mock = fs.readFileSync(path.join(__dirname, "mock-supabase.js"), "utf8");
const movie = { id: 10, title: "Filme de teste", original_title: "Test movie", overview: "Uma história para testar.", poster_path: "/poster.jpg", release_date: "2025-01-01", vote_average: 8, runtime: 120, genres: [{ name: "Drama" }] };
const tv = { ...movie, id: 20, title: undefined, name: "Série de teste", original_name: "Test show", first_air_date: "2024-01-01", number_of_seasons: 2 };
async function main() {
    const server = http.createServer((req, res) => {
        const pathname = decodeURIComponent(new URL(req.url, "http://localhost").pathname);
        const file = path.resolve(root, "." + pathname);
        if (!file.startsWith(root + path.sep)) { res.writeHead(403); res.end(); return; }
        fs.readFile(file, (error, data) => {
            if (error) { res.writeHead(404); res.end(); return; }
            res.setHeader("Content-Type", ({ ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css" })[path.extname(file)] || "application/octet-stream");
            res.end(data);
        });
    });
    await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
    const base = "http://127.0.0.1:" + server.address().port;
    const browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe" });
    const errors = [];
    try {
        const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
        await context.route("https://cdn.jsdelivr.net/**", route => route.fulfill({ contentType: "text/javascript", body: mock }));
        await context.route("https://api.themoviedb.org/**", route => {
            const url = new URL(route.request().url());
            if (url.pathname.endsWith("/999")) return route.fulfill({ status: 404, body: "{}" });
            const item = url.pathname.includes("/tv") ? tv : movie;
            return route.fulfill({ contentType: "application/json", body: JSON.stringify(/\/(movie|tv)\/\d+$/.test(url.pathname) ? item : { page: 1, total_pages: 1, results: url.searchParams.get("query") === "vazio" ? [] : [item] }) });
        });
        await context.route("https://image.tmdb.org/**", route => route.fulfill({ contentType: "image/svg+xml", body: '<svg xmlns="http://www.w3.org/2000/svg" width="500" height="750"><rect width="500" height="750" fill="#345"/><text x="80" y="380" fill="white" font-size="44">CINEPOP</text></svg>' }));
        await context.route("https://test-avatars.invalid/**", route => route.fulfill({ contentType: "image/svg+xml", body: '<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" fill="#00e054"/></svg>' }));
        const page = await context.newPage();
        page.on("pageerror", e => errors.push(e.message));
        const go = async (name) => { await page.goto(base + "/" + name); };
        await go("index.html");
        await page.locator(".card-filme").waitFor();
        assert.equal(await page.locator("#link-perfil").textContent(), "Entrar");
        await page.fill("#pesquisa", "vazio"); await page.click('#form-pesquisa button');
        await page.getByText("Nenhum resultado. Tente outro nome.").waitFor();
        await page.fill("#pesquisa", "teste"); await page.click('#form-pesquisa button');
        await page.locator(".card-filme").click();
        await page.locator("#titulo").filter({ hasText: "Filme de teste" }).waitFor();
        await page.locator("#convite-login").waitFor();
        assert.equal(await page.locator("#acoes-usuario").isVisible(), false);
        await go("midia.html?tipo=movie&id=999");
        await page.getByText("Este título não foi encontrado.").waitFor();
        await go("midia.html?tipo=invalid&id=10");
        await page.getByText("Título inválido.", { exact: false }).waitFor();
        await go("series.html"); await page.getByRole("heading", { name: "Série de teste" }).waitFor();
        await page.evaluate(() => localStorage.setItem("test-user", "yes"));
        await go("midia.html?tipo=movie&id=10"); await page.locator("#acoes-usuario").waitFor();
        await page.click("#watchlist");
        await page.getByRole("button", { name: "Remover da watchlist", exact: true }).waitFor();
        await page.click("#watchlist"); await page.getByRole("button", { name: "+ Watchlist", exact: true }).waitFor();
        await page.click("#favorito");
        await page.getByRole("button", { name: "Remover dos favoritos", exact: true }).waitFor();
        await page.selectOption("#nota", "4"); await page.fill("#review", '<img src=x onerror="alert(1)"> Bom filme');
        await page.check("#spoiler"); await page.click("#salvar-avaliacao");
        await page.getByText("Avaliação salva!", { exact: true }).waitFor();
        assert.match(await page.locator("#media-comunidade").textContent(), /4.0\/5/);
        assert.equal(await page.locator("#reviews img").count(), 0, "Review deve ser texto, nunca HTML");
        await page.selectOption("#nota", "5"); await page.click("#salvar-avaliacao");
        await page.waitForFunction(() => document.querySelector("#media-comunidade").textContent.startsWith("5.0"));
        assert.equal(await page.evaluate(() => window.__state.avaliacoes.length), 1, "Edicao nao duplica avaliacao");
        await page.selectOption("#lista-destino", "1"); await page.click("#adicionar-lista");
        await page.getByText("Título adicionado à lista.", { exact: true }).waitFor();
        assert.equal(await page.evaluate(() => window.__state.lista_midias.length), 1);
        await page.screenshot({ path: path.join(root, ".cinepop-tools/midia-desktop.png"), fullPage: true });
        page.once("dialog", dialog => dialog.accept()); await page.click("#excluir-avaliacao");
        await page.getByText("Avaliação excluída.", { exact: true }).waitFor();
        await go("perfil.html"); await page.locator("#editar-perfil").waitFor();

        await page.waitForFunction(() => document.querySelectorAll("#grafico-notas button").length === 10);
        assert.equal(await page.locator("#total-avaliacoes").textContent(), "0");
        assert.equal(await page.locator("#media-perfil").textContent(), "—");
        await page.evaluate(() => localStorage.setItem("profile-fixture", "yes"));
        await page.reload();
        await page.waitForFunction(() => document.querySelector("#total-avaliacoes").textContent === "4");
        assert.equal(await page.locator("#media-perfil").textContent(), "3,6/5");
        assert.equal(await page.locator("#total-filmes").textContent(), "3");
        assert.equal(await page.locator("#total-series").textContent(), "1");
        assert.deepEqual(await page.locator("#filmes-recentes h3").allTextContents(), ["Titulo 2", "Titulo 3", "Titulo 1"]);
        assert.equal(await page.locator("#tabela-notas tr").count(), 10);
        await page.selectOption("#filtro-ano", "2023");
        assert.equal(await page.locator("#avaliacoes .card-filme").count(), 1);
        await page.click("#limpar-nota");
        await page.locator('[data-nota="4.5"]').click();
        assert.equal(await page.locator("#avaliacoes .card-filme").count(), 2);
        assert.equal(await page.locator('[data-nota="4.5"]').getAttribute("aria-pressed"), "true");
        await page.click("#limpar-nota");
        assert.equal(await page.locator("#avaliacoes .card-filme").count(), 4);
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(root, ".cinepop-tools/perfil-mobile.png"), fullPage: true });
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "Perfil sem rolagem horizontal");
        await page.setViewportSize({ width: 1280, height: 900 });
        await page.locator("#editar-perfil summary").first().click();
        await page.locator("#foto-arquivo").setInputFiles({ name: "arquivo.txt", mimeType: "text/plain", buffer: Buffer.from("invalido") });
        await page.getByText("Escolha uma imagem JPG, PNG ou WebP.").waitFor();
        const png = await page.evaluate(() => {
            const canvas = document.createElement("canvas"); canvas.width = canvas.height = 20;
            const ctx = canvas.getContext("2d"); ctx.fillStyle = "#00e054"; ctx.fillRect(0, 0, 20, 20);
            return canvas.toDataURL("image/png").split(",")[1];
        });
        await page.locator("#foto-arquivo").setInputFiles({ name: "foto.png", mimeType: "image/png", buffer: Buffer.from(png, "base64") });
        await page.getByText("Prévia pronta.", { exact: false }).waitFor();
        assert.equal(await page.evaluate(() => window.__uploads?.length || 0), 0, "Selecionar nao envia foto");
        await page.evaluate(() => window.__failUpload = true);
        await page.click("#salvar-perfil");
        await page.getByText("Não foi possível enviar a foto.", { exact: false }).waitFor();
        assert.equal(await page.locator("#salvar-perfil").isEnabled(), true);
        await page.evaluate(() => { window.__failUpload = false; window.__failProfileSave = true; });
        await page.click("#salvar-perfil");
        await page.getByText("Este registro já existe.", { exact: false }).waitFor();
        assert.equal(await page.evaluate(() => window.__removed.length), 1, "Upload sem perfil salvo deve ser removido");
        await page.evaluate(() => window.__failProfileSave = false);
        await page.click("#salvar-perfil");
        await page.getByText("Perfil atualizado!", { exact: true }).waitFor();
        assert.equal(await page.evaluate(() => window.__uploads[1].type), "image/jpeg");
        assert.match(await page.evaluate(() => window.__state.perfis[0].avatar_url), /^avatars\/11111111-1111-4111-8111-111111111111\/.*\.jpg$/);
        assert.equal(await page.locator("#avatar").isVisible(), true);
        await page.click("#remover-foto"); await page.click("#salvar-perfil");
        await page.waitForFunction(() => window.__state.perfis[0].avatar_url === null);
        assert.equal(await page.locator("#avatar-iniciais").isVisible(), true);
        await page.screenshot({ path: path.join(root, ".cinepop-tools/perfil-desktop.png"), fullPage: true });
        await page.fill("#nome", "Ana Cinema"); await page.fill("#bio", "Minha nova bio"); await page.check("#perfil-privado");
        await page.click("#salvar-perfil"); await page.getByText("Perfil atualizado!", { exact: true }).waitFor();
        assert.equal(await page.locator("#nome-perfil").textContent(), "Ana Cinema");
        await go("amigos.html"); await page.getByRole("heading", { name: "@bia" }).waitFor();
        const follow = page.locator('[data-follow="22222222-2222-4222-8222-222222222222"]');
        await follow.click(); await page.getByRole("button", { name: "Deixar de seguir", exact: true }).waitFor();
        await follow.click(); await page.getByRole("button", { name: "Seguir", exact: true }).waitFor();
        await go("lista.html?id=1"); await page.getByRole("heading", { name: "Para assistir", exact: true }).waitFor();
        await page.locator("#editar-lista summary").click();
        await page.fill("#titulo-edicao", "Minha curadoria"); await page.uncheck("#publica-edicao"); await page.click("#salvar-lista");
        await page.getByText("Lista atualizada.", { exact: true }).waitFor();
        assert.equal(await page.locator("#visibilidade-lista").textContent(), "Lista privada");
        await go("lista.html"); await page.locator("#criar-lista").waitFor(); await page.locator("#criar-lista summary").click();
        await page.fill("#titulo-nova-lista", "Nova lista"); await page.click("#criar-lista-btn"); await page.waitForURL("**/lista.html?id=2");
        await go("index.html"); await page.locator(".card-filme").waitFor();
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(root, ".cinepop-tools/home-mobile.png"), fullPage: true });
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "Sem rolagem horizontal em celular");
        await page.evaluate(() => localStorage.removeItem("test-user"));
        await go("cadastro.html"); await page.fill("#nome", "Teste"); await page.fill("#username", "teste");
        await page.fill("#email", "teste@example.com"); await page.fill("#senha", "abc123"); await page.fill("#confirmar-senha", "abcdef");
        await page.click("#btn-cadastro"); await page.getByText("As senhas não são iguais.").waitFor();
        await page.fill("#confirmar-senha", "abc123"); await page.click("#btn-cadastro");
        await page.getByText("Solicitação recebida!", { exact: false }).waitFor();
        await page.waitForURL("**/login.html");
        await page.fill("#email", "ana@example.com"); await page.fill("#senha", "abc123"); await page.click("#btn-login");
        await page.waitForURL("**/index.html");
        assert.deepEqual(errors, [], "Nenhum erro JavaScript");
        console.log("OK: navegador desktop/mobile; catalogos, busca, erros, avaliacao e spoiler, watchlist, favoritos, perfil, seguidores, listas, cadastro e login. APIs simuladas.");
    } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
