-- SOMENTE PARA TESTES ISOLADOS. Nao executar no Supabase real.
create table if not exists public.perfis (
    id uuid primary key references auth.users(id) on delete cascade,
    username text unique not null,
    nome text,
    bio text,
    avatar_url text,
    created_at timestamptz not null default now()
);


-- =========================
-- MIDIAS
-- filmes e séries usados no CineLog
-- =========================

create table if not exists public.midias (
    id bigint generated by default as identity primary key,

    tmdb_id bigint not null,

    tipo text not null
        check (tipo in ('movie', 'tv')),

    titulo text not null,

    titulo_original text,

    poster_path text,

    backdrop_path text,

    data_lancamento date,

    created_at timestamptz not null default now(),

    unique (tmdb_id, tipo)
);


-- =========================
-- AVALIACOES
-- =========================



create table public.avaliacoes (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    midia_id bigint not null
        references public.midias(id)
        on delete cascade,

    nota numeric(2,1) not null
        check (nota >= 0.5 and nota <= 5),

    review text,

    contem_spoiler boolean not null default false,

    created_at timestamptz not null default now(),

    unique (usuario_id, midia_id)
);


-- =========================
-- DIARIO
-- =========================

create table if not exists public.diario (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    midia_id bigint not null
        references public.midias(id)
        on delete cascade,

    data_assistido date not null,

    nota numeric(2,1)
        check (nota is null or (nota >= 0.5 and nota <= 5)),

    review text,

    reassistido boolean not null default false,

    created_at timestamptz not null default now()
);


-- =========================
-- WATCHLIST
-- =========================

create table if not exists public.watchlist (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    midia_id bigint not null
        references public.midias(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    unique (usuario_id, midia_id)
);


-- =========================
-- FAVORITOS
-- =========================

create table if not exists public.favoritos (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    midia_id bigint not null
        references public.midias(id)
        on delete cascade,

    posicao integer,

    created_at timestamptz not null default now(),

    unique (usuario_id, midia_id)
);


-- =========================
-- SEGUIDORES
-- =========================

create table if not exists public.seguidores (
    id bigint generated by default as identity primary key,

    seguidor_id uuid not null
        references public.perfis(id)
        on delete cascade,

    seguido_id uuid not null
        references public.perfis(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    unique (seguidor_id, seguido_id),

    check (seguidor_id <> seguido_id)
);


-- =========================
-- CURTIDAS EM REVIEWS
-- =========================

create table if not exists public.likes_avaliacoes (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    avaliacao_id bigint not null
        references public.avaliacoes(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    unique (usuario_id, avaliacao_id)
);


-- =========================
-- COMENTARIOS
-- =========================

create table if not exists public.comentarios (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    avaliacao_id bigint not null
        references public.avaliacoes(id)
        on delete cascade,

    texto text not null,

    created_at timestamptz not null default now()
);


-- =========================
-- LISTAS
-- =========================

create table if not exists public.listas (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    titulo text not null,

    descricao text,

    publica boolean not null default true,

    created_at timestamptz not null default now()
);


-- =========================
-- FILMES / SERIES DAS LISTAS
-- =========================

create table if not exists public.lista_midias (
    id bigint generated by default as identity primary key,

    lista_id bigint not null
        references public.listas(id)
        on delete cascade,

    midia_id bigint not null
        references public.midias(id)
        on delete cascade,

    posicao integer,

    created_at timestamptz not null default now(),

    unique (lista_id, midia_id)
);


-- =========================
-- LIKES EM LISTAS
-- =========================

create table if not exists public.likes_listas (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    lista_id bigint not null
        references public.listas(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    unique (usuario_id, lista_id)
);


-- =========================
-- NOTIFICACOES
-- =========================

create table if not exists public.notificacoes (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.perfis(id)
        on delete cascade,

    autor_id uuid
        references public.perfis(id)
        on delete cascade,

    tipo text not null,

    referencia_id bigint,

    mensagem text,

    lida boolean not null default false,

    created_at timestamptz not null default now()
);


-- =========================
-- CONFIGURACOES
-- =========================

create table if not exists public.configuracoes (
    usuario_id uuid primary key
        references public.perfis(id)
        on delete cascade,

    perfil_privado boolean not null default false,

    notificacao_seguidor boolean not null default true,

    notificacao_like boolean not null default true,

    notificacao_comentario boolean not null default true,

    tema text not null default 'dark'
        check (tema in ('dark', 'light'))
);